### ISSUE TITLE
Open License?

### ISSUE THREAD

**Issue by xavidp** [BruceZhaoR/mypkg#1]
Dear  Bruce Zhao,

First of all, thanks for sharing this package of yours. I was looking for a simple yet effective way to convert png's to svg's, and you've just done it in your png2svg.R file. Thanks.

I'd like to reuse your function, but your package seems just some unfinished demo while your are learning how to make R packages. So I'd just take your R file for my own uses (so far, teaching an introductory course of R for civil servants in the Barcelona City Council, Catalonia, Spain, Europe - https://gitlab.com/radup/curs-r-introduccio ). 

In addition, I see that you indicate a copyright license for your package which is unclear to me:
https://github.com/BruceZhaoR/mypkg/blob/master/LICENSE

YEAR: 2018
COPYRIGHT HOLDER: Shanghai PingJia Technology Co.,Ltd.

You are allowing others to copy and use your code, at least, and the previous license sounds as "all rights reserved", while your blog is cc-by-nc-sa. I'd like to ask you to share your png2svg (or package) as MIT license or similar.

What do you think?

Thanks!

Xavier (aka xavidp @ github and gitlab)

**Comment by BruceZhaoR** [comment]
@xavidp  Change it to MIT. I'm happy that my code will be used by others. This repo is just for testing.
Here is my completed R pkg: <https://github.com/BruceZhaoR/pjutils>
